# Generated by Django 2.2.16 on 2022-04-29 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_auto_20220429_1914'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Genre',
        ),
        migrations.RemoveField(
            model_name='title',
            name='category',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
