# Generated by Django 2.2.16 on 2022-04-30 18:08

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reviews', '0008_auto_20220430_1930'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='review',
            name='unique follow',
        ),
        migrations.AlterUniqueTogether(
            name='review',
            unique_together={('author', 'title')},
        ),
    ]
